[[headers]]
  for = "*.css"

  [headers.values]
    Cache-Control = "public, max-age=900"

[[headers]]
  for = "*.js"

  [headers.values]
    Cache-Control = "public, max-age=900"

[[headers]]
  for = "*.png"

  [headers.values]
    Cache-Control = "public, max-age=900"

[[headers]]
  for = "*.gif"

  [headers.values]
    Cache-Control = "public, max-age=900"

[[headers]]
  for = "*.jpg"

  [headers.values]
    Cache-Control = "public, max-age=900"

[[headers]]
  for = "*.svg"

  [headers.values]
    Cache-Control = "public, max-age=900"

[[redirects]]
from = "/swiss-python-summit-2024/schedule"
to = "https://pretalx.sifs0005.infs.ch/swiss-python-summit-2024/schedule/"
status = 302
